### ISSUE TITLE
 Can you please clarify me the License Conditions in practical terms?

### ISSUE THREAD

**Issue by raphael10-collab** [apache/incubator-annotator#106]
It's not clear to me the license: 

Here: https://github.com/apache/incubator-annotator/blob/master/LICENSE

![image](https://user-images.githubusercontent.com/70313067/111280943-b2271e80-863c-11eb-9056-7cb7e7f17f8d.png)

I read that it's an Apache License 2.0, with all related implications. 

I thought that the permissions of the Apache License 2.0 were clear and evident enough: Commercial Use, Modification,Distribution,Patent Use, and Private Use, with Limitations: Trademark Use, Liability, Warranty, and its Conditions: State Changes, License and Copyright notice.

But here : https://www.npmjs.com/package/apache-annotator#disclaimer

I read : "If you are planning to incorporate this work into your product/project, please be aware that you will need to conduct a thorough licensing review to determine the overall implications of including this work.".
What does this mean in practical terms?

I've read also this thread: https://github.com/apache/incubator-annotator/issues/63 
but it didn't clarify me much.

Can you please clarify me?

**Comment by tilgovi** [comment]
The disclaimer must be provided by Apache projects during incubation because some Apache projects may have code that was not licensed as Apache License 2.0 at the time the project moved to Apache. Those projects may need to go through a process of re-licensing components or appending the project notifications to their license files and notice files. The intention of the disclaimer is to allow incubating projects to make releases without necessarily having identified and resolved all such issues.

Annotator has no outside work that would be under any other license, but we are required to provide the disclaimer during the incubation process. The disclaimer is there so that you know that the Apache Software Foundation does not guarantee that our license is complete and accurate and that you may wish to inspect the code to make your own determination as to whether the LICENSE and NOTICE files completely describe the correct status of the work.

**Comment by tilgovi** [comment]
For example, the Apache Annotator was originally considered to be a potential home for the older Annotator.js project, but all the contributors have instead determined to implement things from scratch, with inspiration (but not code) from the Annotator.js project.

Therefore, it is my belief that all of our code is properly under the Apache License 2.0, but the foundation has not done a thorough review as part of a process whereby the project would graduate from incubation to full project of the foundation.

**Comment by tilgovi** [comment]
@raphael10-collab I'm going to close this, but please follow up if you have further questions!

**Comment by raphael10-collab** [comment]
Thank you for your kind explanation
