### ISSUE TITLE
How to keep selection range when DOM change for unchangeable article?

### ISSUE THREAD

**Issue by webbery** [apache/incubator-annotator#14]
Hi, this may be an enchancement. Because I have no idea how to impliment it. 
I have selected a range while other annotated part of my selection. If I used websocket to show these DOM changes, can I keep my selection?

**Comment by tilgovi** [comment]
Thanks for raising this issue.

Right now there is very little in this repository other than some sample / demo code and a package for parsing and serializing selector fragments.

Are you looking for help with Annotator.js, perhaps?

**Comment by webbery** [comment]
I use annotator.js of open annotator. But I do not update annotation simultaneously. If selection save as a node before update, it may be separated to two parts which can only select one of them in chrome.

Because of that, it is still an idea I'm not implimented.

**Comment by tilgovi** [comment]
You are looking for a different repository: https://github.com/openannotation/annotator

**Comment by webbery** [comment]
Yes, I have used that repository in my nodejs project. And I'm not sure that my new idea can be implemented or not. Because this repository doesn't update for a long time. W3C create a new annotation standard. 

This incubator will be better than openannotation. So I think it may have some way to keeping selection? :)

**Comment by tilgovi** [comment]
@webbery thank you again for bringing up your needs here. I'm going to close this issue because there is not a concrete action to take. This repository is very new but it's being designed with this kind of use case in mind.

When we get close to our first release I'll go back through these issues and make sure to comment so that you and anyone else who is waiting to test the new packages can check that it addresses your needs.
