### ISSUE TITLE
Ability to use multiple layers of annotation.

### ISSUE THREAD

**Issue by bjonnh** [apache/incubator-annotator#21]
This kind of thing cannot be represented in a DOM easily, unless we have a tree and a way for each tree to just represent the index of the annotations in it.

Working in a DOM:
<annotation type="important_sentence">The <annotation type="animal">cat</annotation> is on the <annotation type="place">roof</annotation></annotation> 

Not working in a DOM:
 <anno1>.....<anno2>.....</anno1>.....</anno2>   

I was envisionning something similar to (not following any W3C recommendation here, just an idea)
<text>
Something is here
<annotations>
<annotation_layer><annotation type="verb" start_index="9" end_index="11">is</annotation></annotation_layer>
<annotation_layer><annotation type="sentence" start_index="0" end_index="-1">Something is here</annotation></annotation_layer>
<annotation_layer><annotation type="beginning" start_index="0" end_index="11">Something is</annotation></annotation_layer>
<annotation_layer><annotation type="end" start_index="9" end_index="15">is here</annotation></annotation_layer>
</annotations>
</text>

But copying the text over and over is probably not a good idea…

**Comment by BigBlueHat** [comment]
The way this has been done in the past (afaik) is to keep references to the groups of DOM nodes that represent a single annotation--and juggle all the interleaved DOM nodes if/when anything changes. It's beyond inefficient, but it's what happens when you cram to trees together...

So, from your example, you'd end up with something like this (pseudo code here also):
```html
<p><mark data-anno-id="3">Something </mark><mark data-anno-id="1"><mark data-anno-id="3"><mark data-anno-id="2">is</mark></mark><mark data-anno-id="3"> here</mark></mark></p>

<p><mark data-anno-id="345">And there's more text</mark> down here</p>
```

Lovely, right? 😉 The text in each selection would be:
1. "is"
2. "is here"
3. "Something is here And there's more text"

Presented as a tree this looks like:
```html
<p>
  <mark data-anno-id="3">Something </mark>
  <mark data-anno-id="1">
    <mark data-anno-id="3">
      <mark data-anno-id="2">is</mark>
    </mark>
    <mark data-anno-id="3"> here</mark>
  </mark>
</p>

<p>
  <mark data-anno-id="345">And there's more text</mark>
  down here
</p>
```

The DOM will think of (and treat) several of these `<mark>` tags as parents or children of other `<mark>` tags. The annotation software, however, would treat them as unrelated and remove/add/change their occurrences wherever they're found. Finding them is one thing (`document.querySelectorAll('[data-anno-id=3]`) creating them interleaved inside other stuff is entirely another...

**Comment by tilgovi** [comment]
This is helpful context for whomever wants to implement a highlighter, but we haven't got one yet. The demo adds `mark` do documents as an example of what could be done with the result of selection, but there's no exposed highlighter API yet.

Where does that leave us with this issue? Is there more to discuss here right now? Would it be helpful for me to leave it open?

**Comment by BigBlueHat** [comment]
I think let's leave it open and begin planning/coding a highlighter. It's a super hard piece of this puzzle, and having that done will mean more annotation tools (built on Apache Annotator ta boot!). 😉

**Comment by Treora** [comment]
We do have a simple highlighter now, using the `<mark>`-based approach, which could be used for overlapping annotations as described [above](https://github.com/apache/incubator-annotator/issues/21#issuecomment-348224795).

Unless I overlook a relevant nuance, this issue and #47 (“Interleaving selections within the DOM”) seem pretty much the same topic; closing this one.
