### ISSUE TITLE
Multiple packages have conflicting node version dependency

### ISSUE THREAD

**Issue by salus-sage** [apache/incubator-annotator#34]
i was unable to proceed further than yarn install, i'm interested to contribute to the project but unable to setup the environment. i tried on node version @6.11.5 and yarn @1.5.1
```
error @shellscape/koa-static@4.0.4: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
error An unexpected error occurred: "Found incompatible module".
```
And when i try with node 7.6.0, i get below error,
![screenshot 25](https://user-images.githubusercontent.com/6399323/41587611-3c173394-73cd-11e8-8ad2-7ef9066d800d.png)

**Comment by BigBlueHat** [comment]
It looks like Yarn skipped the node 7.x series of releases (for reasons I don't know...). The [Yarn site](https://yarnpkg.com/en/) states that same list of semver ranges:
>  Node: ^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0

Consequently, if you move to 8.x, things should "just work."

Modules we depend on (such as `koa-static`...apparently) will all declare their own minimum node version, but yarn won't run unless it's one of those four.

Given that `koa-static` needs > 7.x (which may be a new dependency... @tilgovi ? @Treora ?), we may need to bump our requirements up to 8.x (rather than 6.x as stated here):
https://github.com/apache/incubator-annotator#requirements

Regardless, moving to node 8.x (if you can) should fix that current situation.

**Comment by tilgovi** [comment]
I'll double check in a bit, but I'm almost positive this is only a development dependency, which means we should not change our requirements. We may need to document the development requirement, though.

**Comment by salus-sage** [comment]
Thanks for the swift response,
worked for node @ 8.1.0
failed for node @ 8.0.0,
