### ISSUE TITLE
Import @tilgovi's dom-anchor-* libraries

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#38]
This has been part of the plan since day one (or earlier 😉).

Now that we've got our [npm org](https://www.npmjs.com/org/annotator) up and running, let's close this loop.

@tilgovi are you still able to make this happen?

See https://github.com/apache/incubator-annotator/issues/25#issuecomment-358420732

**Comment by tilgovi** [comment]
Definitely.

**Comment by tilgovi** [comment]
I propose we bump this out of the first release. Let's just get the basics. I'm not yet sure whether those packages have the right API for us.

**Comment by Treora** [comment]
Relatedly, as I just wrote on the [dev mailing list](https://mail-archives.apache.org/mod_mbox/annotator-dev/201906.mbox/browser):

> Do you have, or else shall we perhaps create, an overview of the modules we want to create, and how they relate to each other? That way we would have a clear reason why we have and maintain each module. In the attached graph, I sketched the relations between the mentioned modules (as I understand them), while already adding two hypothetical candidates in grey.

But as the dev mailing list appears not to support attaching images, I hope it helps if I post the graph here:

![modules-overview](https://user-images.githubusercontent.com/4191409/60297298-2b8e5300-9928-11e9-906d-aba867b05d6d.png)

**Comment by Treora** [comment]
Just discussed in the weekly call: rather than importing these modules as such, we better just get at (and beyond) feature parity and thereby make them obsolete.

For the missing functionalities see their relevant issues:
- dom-anchor-text-position: see #75 
- dom-anchor-text-quote: we lack fuzzy matching, see #83 
- dom-anchor-fragment: does anybody actually use this? Open an issue if so. :) (it seems Hypothes.is [dropped](https://github.com/hypothesis/client/commit/f8784b2c8837f67b82866c63b74215bc90739653) it)
