### ISSUE TITLE
Add apache-annotator meta-package

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#90]
In order to follow suggestions for releasing npm packages as `apache-<project>` without violating the spirit of producing convenience packages from released source code, I copied, unmodified, the two packages (selector and dom) into subdirectories of a new `apache-annotator` package and published that to GitHub with an abridged README.

If we complete #89, I think it should be safe to publish the individual packages to the annotator scope on npm because the individual packages will all make clear that they belong to apache-annotator. However, even leaving aside policy motivations it is a great convenience to users if we have a meta-package, I think, especially while we are still experimenting with our internal code organization.

Let's check in an apache-annotator meta-package with a clear README and have it depend on the other packages. That will get us in a place to publish directly and simply with lerna for the next release.

**Comment by Treora** [comment]
What exactly would a meta-package provide? Should it be just like the current apache-annotator that you published to npm, and the issue is simply to automate its publishing process?

The current meta-package would be used as: `import dom from 'apache-annotator/dom';`. Shall we keep it like that, or would you prefer to change it to `import { dom } from 'apache-annotator';`? Or something else?

**Comment by tilgovi** [comment]
Closed by #94.
