### ISSUE TITLE
Generate TypeScript API documentation

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#97]
Using tools from the microsoft/tsdoc ecosystem, create scripts to generate TypeScript API documentation.

**Comment by Treora** [comment]
@tilgovi Could you share/describe your attempt with tsdoc so far? I am curious what you used if not `api-documenter`, because it [looks like][1] `@microsoft/tsdoc` is not made for direct consumption:

> By itself, the @microsoft/tsdoc package is not a documentation solution you can use directly. It is an engine component used by other tools such as API Extractor. The NPM dependency report is an easy way to find tools that implement TSDoc.

Upon quick inspection I don’t see anything listed that look more mature than the api-documenter I tried in #101, but would be glad to find something nicer (it gets the job done though)

[1]: https://tsdoc.org/pages/intro/using_tsdoc/

**Comment by Treora** [comment]
Oh wait, there’s tsdoc.org and there is typedoc.org; please excuse my confusion. :) I suppose that’s what you tried; I’d be glad to try both and compare. It may still be helpful to see your setup, if you could push that as a branch.
